# Generated by Django 5.0.10 on 2025-02-26 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSC1',
            fields=[
                ('recno', models.AutoField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('C1_NUM', models.CharField(max_length=6)),
                ('C1_COTACAO', models.CharField(max_length=6)),
                ('C1_QUJE', models.FloatField()),
                ('C1_APROV', models.CharField(max_length=1)),
                ('C1_QUANT', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('C1_RESIDUO', models.CharField(default='N', max_length=1)),
                ('C1_IMPORT', models.CharField(default='N', max_length=1)),
                ('C1_COMPRAC', models.CharField(default='2', max_length=1)),
            ],
            options={
                'db_table': 'SC1010',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('c1_filial', models.CharField(default='0101', max_length=4)),
                ('c1_num', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('c1_solicit', models.CharField(default='000000', max_length=6)),
                ('c1_emissao', models.DateField()),
                ('tipo', models.CharField(default='Compra', max_length=15)),
                ('status', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateioSC',
            fields=[
                ('cx_filial', models.CharField(default='0101', max_length=4)),
                ('cx_itemsol', models.CharField(max_length=4)),
                ('cx_item', models.CharField(max_length=2)),
                ('cx_perc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cx_cc', models.CharField(default='', max_length=9)),
                ('cx_conta', models.CharField(default='', max_length=20)),
                ('cx_itemcta', models.CharField(default='', max_length=9)),
                ('cx_clvl', models.CharField(default='', max_length=9)),
                ('r_e_c_n_o', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('cx_solicit', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='solicitacoes.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('c1_item', models.CharField(max_length=4)),
                ('c1_produto', models.CharField(max_length=15)),
                ('c1_descri', models.CharField(max_length=50)),
                ('c1_um', models.CharField(max_length=2)),
                ('c1_filent', models.CharField(default='0101', max_length=4)),
                ('c1_local', models.CharField(max_length=2)),
                ('b1_conta', models.CharField(max_length=20)),
                ('c1_quant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('c1_cc', models.CharField(default='', max_length=60)),
                ('c1_datprf', models.DateField(default='2025-01-01')),
                ('ctj_desc', models.CharField(default='', max_length=40)),
                ('c1_obs', models.TextField(default='')),
                ('r_e_c_n_o', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('c1_num', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='solicitacoes.solicitacao')),
            ],
        ),
    ]
