# Generated by Django 5.0.10 on 2025-02-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statussc1',
            name='C1_FILENT',
            field=models.CharField(default='0101', max_length=4),
        ),
        migrations.AddField(
            model_name='statussc1',
            name='C1_ITEM',
            field=models.CharField(default='0001', max_length=4),
        ),
    ]
