# Generated by Django 5.0.10 on 2025-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
