# Generated by Django 5.0.10 on 2024-12-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='user',
            new_name='solicitante',
        ),
    ]
