# Generated by Django 5.0.10 on 2024-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSC1',
            fields=[
                ('recno', models.AutoField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('C1_NUM', models.CharField(max_length=6)),
                ('C1_COTACAO', models.CharField(max_length=6)),
                ('C1_QUJE', models.FloatField()),
                ('C1_APROV', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'SC1010',
            },
        ),
    ]
