# Generated by Django 5.0.10 on 2025-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_statussc1_c1_filent_statussc1_c1_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='c1_cc',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ctj_desc',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
