# Generated by Django 5.0.10 on 2025-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='c1_rateio',
            field=models.CharField(default='', max_length=40),
        ),
    ]
