# Generated by Django 5.0.10 on 2025-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_produto_c1_cc_alter_produto_ctj_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='c1_cc',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ctj_desc',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
