# Generated by Django 5.0.10 on 2024-12-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_solicitacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c7_num', models.CharField(max_length=6)),
                ('c7_quje', models.FloatField()),
                ('c7_qtdacla', models.FloatField()),
                ('c7_conapro', models.CharField(max_length=1)),
                ('c7_tipo', models.CharField(max_length=1)),
                ('c7_residuo', models.CharField(max_length=1)),
                ('c7_quant', models.FloatField()),
                ('c7_contra', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'SC7010',
                'managed': False,
            },
        ),
    ]
