# Generated by Django 5.0.10 on 2024-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_statuspedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='c1_filent',
            field=models.CharField(default='0101', max_length=4),
        ),
    ]
