# Generated by Django 5.0.10 on 2024-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_rename_solicitante_solicitacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='c1_obs',
            field=models.CharField(default='', max_length=30),
        ),
    ]
