# Generated by Django 5.0.10 on 2025-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_alter_produto_c1_cc_alter_produto_ctj_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ctj_desc',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
