# Generated by Django 5.0.10 on 2025-02-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_produto_ctj_desc_alter_produto_c1_rateio'),
        ('solicitacoes', '0005_alter_solicitacao_user'),
    ]

    operations = [
    ]
