# Generated by Django 5.0.10 on 2024-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_alter_solicitacao_c1_datprf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='c1_datprf',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='c1_emissao',
            field=models.CharField(max_length=8),
        ),
    ]
