# Generated by Django 5.0.10 on 2025-02-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_merge_20250213_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='c1_rateio',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ctj_desc',
        ),
    ]
