# Generated by Django 5.0.10 on 2025-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_remove_produto_c1_rateio_remove_produto_ctj_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ctj_desc',
            field=models.CharField(default='', max_length=40),
        ),
    ]
