# Generated by Django 5.0.10 on 2025-02-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_produto_ctj_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='b1_conta',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RateioSC',
            fields=[
                ('cx_filial', models.CharField(default='0101', max_length=4)),
                ('cx_itemsol', models.CharField(max_length=4)),
                ('cx_item', models.CharField(max_length=2)),
                ('cx_perc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cx_cc', models.CharField(default='', max_length=9)),
                ('cx_conta', models.CharField(default='', max_length=20)),
                ('cx_itemcta', models.CharField(default='', max_length=9)),
                ('cx_clvl', models.CharField(default='', max_length=9)),
                ('r_e_c_n_o', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('cx_solicit', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='solicitacoes.solicitacao')),
            ],
        ),
    ]
