# Generated by Django 5.0.10 on 2025-02-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_produto_ctj_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='usa_rateio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(max_length=60)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='solicitacoes.configuracaorateio')),
            ],
        ),
        migrations.CreateModel(
            name='RateioProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(max_length=60)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='solicitacoes.produto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemrateio',
            constraint=models.UniqueConstraint(fields=('configuracao', 'centro_custo'), name='unique_centro_custo_por_config'),
        ),
        migrations.AddConstraint(
            model_name='rateioproduto',
            constraint=models.UniqueConstraint(fields=('produto', 'centro_custo'), name='unique_centro_custo_por_produto'),
        ),
    ]
