# Generated by Django 5.0.10 on 2025-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0009_produto_b1_conta_rateiosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='c1_obs',
            field=models.TextField(default=''),
        ),
    ]
