# Generated by Django 5.0.10 on 2025-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0010_alter_produto_c1_obs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusPedido',
        ),
        migrations.AddField(
            model_name='statussc1',
            name='C1_COMPRAC',
            field=models.CharField(default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='statussc1',
            name='C1_IMPORT',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='statussc1',
            name='C1_QUANT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='statussc1',
            name='C1_RESIDUO',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
