# Generated by Django 5.0.10 on 2025-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0011_delete_statuspedido_statussc1_c1_comprac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statussc1',
            name='delete',
            field=models.CharField(default='', max_length=1),
        ),
    ]
