# Generated by Django 5.0.10 on 2025-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0013_alter_statussc1_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='statussc1',
            name='C1_ITEM',
            field=models.CharField(default='0001', max_length=4),
        ),
    ]
