# Generated by Django 5.1.4 on 2024-12-15 03:19

import utils.cpf_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[utils.cpf_funcs.cpf_validate])),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
