# Generated by Django 5.1.4 on 2024-12-17 01:28

import utils.cpf_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, validators=[utils.cpf_funcs.cpf_validate]),
        ),
    ]
