# Generated by Django 5.0.10 on 2024-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [{'Pode ver todas as solicitações', 'ver_todas_solicitacoes'}, {'Pode criar novos usuários', 'criar_novos_usuários'}]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('default', 'Padrão')], default='default', max_length=20),
        ),
    ]
