# Generated by Django 5.0.13 on 2025-03-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('ver_todas_solicitacoes', 'Pode ver todas as solicitações'), ('criar_novos_usuários', 'Pode criar novos usuários')]},
        ),
    ]
