# Generated by Django 5.0.10 on 2025-01-02 17:53

import utils.cpf_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_id_alter_customuser_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, validators=[utils.cpf_funcs.cpf_validate]),
        ),
    ]
