# Generated by Django 5.0.10 on 2024-12-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_activesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
