# Generated by Django 5.0.10 on 2025-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_id_alter_customuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=None, editable=False, max_length=6, unique=True),
        ),
    ]
