# Generated by Django 5.0.10 on 2024-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_num', models.CharField(max_length=6)),
                ('c1_cc', models.CharField(default='', max_length=60)),
                ('c1_item', models.CharField(max_length=4)),
                ('c1_produto', models.CharField(max_length=60)),
                ('c1_descri', models.CharField(default='', max_length=50)),
                ('c1_local', models.CharField(max_length=2)),
                ('c1_quant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('c1_datprf', models.DateField()),
                ('r_e_c_n_o', models.BigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
