# Generated by Django 5.1.4 on 2024-12-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Compras', 'COMPRAS'), ('Armazém', 'ARMAZEM')], default='COMPRAS', max_length=100)),
                ('produto', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_de_necessidade', models.DateField()),
                ('obs', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pendente', 'PENDENTE'), ('Aprovado', 'APROVADO'), ('Rejeitado', 'REJEITADO')], default='', max_length=100)),
            ],
        ),
    ]
