# Generated by Django 5.1.4 on 2024-12-15 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_de_necessidade', models.DateField()),
                ('obs', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('Rejeitado', 'REJEITADO')], default='', max_length=100)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.user')),
            ],
        ),
    ]
