# Generated by Django 5.0.10 on 2024-12-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitacao',
        ),
    ]
