# Generated by Django 5.1.4 on 2024-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('Aprovado', 'APROVADO'), ('REJEITADO', 'Rejeitado')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('Compras', 'COMPRAS'), ('ARMAZEM', 'Armazém')], default='COMPRAS', max_length=100),
        ),
    ]
