# Generated by Django 5.0.10 on 2024-12-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitacao',
        ),
    ]
