# Generated by Django 5.1.4 on 2024-12-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_solicitacao_status_alter_solicitacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('Aprovado', 'APROVADO'), ('Rejeitado', 'REJEITADO')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('Compras', 'COMPRAS'), ('Armazém', 'ARMAZEM')], default='COMPRAS', max_length=100),
        ),
    ]
