# Generated by Django 5.1.4 on 2024-12-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_solicitacao_status_alter_solicitacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('COMPRAS', 'Compras'), ('Armazém', 'ARMAZEM')], default='COMPRAS', max_length=100),
        ),
    ]
